# Main configuration file for HaloPlex analysis
bwa:
  aln:
    parent_task: ratatosk.misc.ResyncMatesJobTask

misc:
  ResyncMates:
    parent_task: ratatosk.cutadapt.CutadaptJobTask

samtools:
  SamToBam:
    parent_task: ratatosk.scilife.seqcap.HaloBwaSampe

picard:
  SortSam:
    parent_task: ratatosk.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.picard.SortSam
  DuplicationMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  HsMetrics:
    parent_task: ratatosk.picard.MergeSamFiles

gatk:
  # These are all subclassed for Halo, see dependencies below
  # RealignerTargetCreator:
  #   parent_task: ratatosk.picard.MergeSamFiles
  # IndelRealigner:
  #   parent_task: ratatosk.gatk.RealignerTargetCreator
  # BaseRecalibrator:
  #   parent_task: ratatosk.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.gatk.VariantFiltration

  # Addon tasks needed for HaloPlex
  RawUnifiedGenotyper:
    parent_task: ratatosk.picard.MergeSamFiles
  RawRealignerTargetCreator:
    parent_task: ratatosk.picard.MergeSamFiles
  RawIndelRealigner:
    parent_task: ratatosk.picard.MergeSamFiles
  # Finally, make BaseRecalibrator depend on RawIndelRealigner
  BaseRecalibrator:
    parent_task: ratatosk.scilife.seqcap.RawIndelRealigner
