# Main configuration file
bwa:
  bwaref: ../ngs_test_data/data/genomes/Hsapiens/hg19/bwa/chr11.fa
  #bwaref: ../../../genomes/Hsapiens/hg19/bwa/chr11.fa

samtools:
  SamToBam:
    parent_task: ratatosk.samtools.SampeToSamtools

picard:
  DuplicationMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  SortSam:
    parent_task: ratatosk.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.picard.SortSam

gatk:
  #ref: ../../ngs_test_data/data/genomes/Hsapiens/hg19/seq/chr11.fa
  #knownSites: [../../ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf]
  #dbsnp: ../../ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf
  ref: ../../../genomes/Hsapiens/hg19/seq/chr11.fa
  knownSites: [../../../genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf]
  dbsnp: ../../../genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf

  RealignmentTargetCreator:
    parent_task: ratatosk.picard.MergeSamFiles
  IndelRealigner:
    parent_task: ratatosk.gatk.RealignmentTargetCreator
  BaseRecalibrator:
    parent_task: ratatosk.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.gatk.UnifiedGenotyper
