# Main configuration file
bwa:
  #bwaref: ../ngs_test_data/data/genomes/Hsapiens/hg19/bwa/chr11.fa
  bwaref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/bwa/chr11.fa

samtools:
  SamToBam:
    parent_task: ratatosk.bwa.BwaSampe

picard:
  DuplicationMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.picard.MergeSamFiles
  SortSam:
    parent_task: ratatosk.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.picard.SortSam

gatk:
  ref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seq/chr11.fa
  knownSites: [~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf]
  dbsnp: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf
  #ref: ../../../genomes/Hsapiens/hg19/seq/chr11.fa
  #knownSites: [../../../genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf]
  #dbsnp: ../../../genomes/Hsapiens/hg19/variation/dbsnp132_chr11.vcf

  RealignerTargetCreator:
    #parent_task: ratatosk.picard.DuplicationMetrics
    parent_task: ratatosk.picard.MergeSamFiles
  IndelRealigner:
    parent_task: ratatosk.gatk.RealignerTargetCreator
  BaseRecalibrator:
    parent_task: ratatosk.gatk.IndelRealigner
  PrintReads:
    parent_task: ratatosk.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.gatk.VariantFiltration
