# Note: currently you need to set the reference path manually. Look
# for folder data/genomes in your ngstestdata installation location
bwa:
  bwaref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/bwa/chr11.fa

gatk:
  UnifiedGenotyper:
    ref: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seq/chr11.fa

picard:
  # InputBamFile "pipes" input from other modules
  InputBamFile:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
    targets: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seqcap/chr11_targets.interval_list
    baits: ~/opt/ngs_test_data/data/genomes/Hsapiens/hg19/seqcap/chr11_baits.interval_list

samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.BwaSampe
